# Generated by Django 5.2.5 on 2025-10-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
