# Generated by Django 5.2.5 on 2026-01-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_content_link_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdf/', verbose_name='Файл'),
        ),
    ]
