# Generated by Django 5.2.5 on 2026-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.TextField(),
        ),
    ]
