# Generated by Django 5.2.5 on 2026-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_content_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
