# Generated by Django 5.2.5 on 2026-04-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_content_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.IntegerField(default=3),
        ),
    ]
