"""
Django settings for domashkola project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p(!yd4q=!vyh4$@vh(&(+#)$77r#i!$p17s@8sl3owrt1ug(f9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Application definition

# instructions for Django debugger toolbar
# import sys
# import os
# TESTING = "test" in sys.argv or "PYTEST_VERSION" in os.environ


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storage.apps.StorageConfig',
    'android.apps.AndroidConfig',
    'accounts.apps.AccountsConfig',
    # 'debug_toolbar',
    'crispy_forms',
]

MIDDLEWARE = [
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'domashkola.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'domashkola.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'u3160041_domashkola_django',
        'USER': 'u3160041_domashkola_admin',
        'PASSWORD': 'ramsey24041989',
        'HOST': '127.0.0.1',
    }
}

# Authentication

AUTHENTICATION_BACKENDS = [
    # 'django.contrib.auth.backends.ModelBackend',
    'accounts.authentication.EmailAuthBackend',
]

AUTH_USER_MODEL = 'accounts.User'


# настройки вашего SMTP сервера
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465   # или 465 для SSL
EMAIL_HOST_USER = 'family-school-92@yandex.ru'
# EMAIL_FROM_ADDRESS = ''
EMAIL_HOST_PASSWORD = 'csmxcrfwfjjonvfy'
EMAIL_USE_SSL = True    # или EMAIL_USE_SSL = True, если используете SSL
ACCOUNT_EMAIL_UNIQUE = False    # если email является уникальным
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = False
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

# используется для тестирования
# выводит письма в консоли
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_FILE_PATH = BASE_DIR / "emails"


# DEFAULT_FROM_EMAIL = 'Your Project Name <your-email@example.com>'

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'  # После выхода
LOGIN_URL = 'accounts/login/'   # если неавторизованный посетитель попытается зайти на закрытую страницу сайта

CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'RU-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# # STATIC_URL = '/domashkola/static/'
# # STATIC_ROOT = 'domashkola/static/'
# STATIC_URL = 'static/'
# STATIC_ROOT = '/static/'

# MEDIA_ROOT = 'media/'
# MEDIA_URL = '/media/'


# STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "static"),
# ]

STATIC_URL = 'static/'
STATICFILES_DIRS = [
   BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]
