# Generated by Django 5.2.5 on 2025-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=3)),
                ('subject', models.CharField(max_length=10)),
                ('presentation', models.CharField(max_length=10)),
                ('formatData', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
