# Generated by Django 5.2.5 on 2025-09-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=35)),
                ('subject_code', models.CharField(max_length=10)),
            ],
        ),
    ]
