# Generated by Django 5.2.5 on 2025-09-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=20)),
                ('grade_code', models.CharField(max_length=3)),
            ],
        ),
    ]
