# Generated by Django 5.2.5 on 2025-09-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='formatData',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='grade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='presentation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.CharField(max_length=35),
        ),
    ]
