# Generated by Django 5.2.5 on 2025-09-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_content_formatdata_alter_content_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_name', models.CharField(max_length=20)),
                ('presentation_code', models.CharField(max_length=10)),
            ],
        ),
    ]
