# Generated by Django 5.2.5 on 2025-09-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(max_length=20)),
                ('format_code', models.CharField(max_length=10)),
            ],
        ),
    ]
